on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 3 * *"

name: Build LaTeX document using dante-ev's Action

jobs:
  build_latex:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install texcount
        run: sudo apt-get install texlive-extra-utils

      - name: Unzip Springer zip
        run: unzip style/contributed-books.zip

      #############################################
      # See if all files are there
      #############################################

      - name: Check file existence
        uses: andstor/file-existence-action@v2
        with:
          files: svmult.cls
          fail: true

      - name: Doublecheck the existence of svmult.cls
        run: ls *.cls

      - name: Triplecheck the existence of svmult.cls
        run: cat svmult.cls

      - name: Copy author/svind.ist from unzipped Springer zip
        run: cp author/svind.ist svind.ist

      # (2) a subdirectory "styles" with
      #- the Springer MakeIndex style file "svind.ist"
      #- the Springer MakeIndex style file "svindd.ist" - german version
      #- the Springer BibTeX styles "spbasic.bst", "spmpsci.bst", "spphys.bst"
      - name: Check file existence of svind.ist
        uses: andstor/file-existence-action@v2
        with:
          files: svind.ist
          fail: true

      - name: Count number of words
        run: texcount article.tex

      #############################################
      # From Springer: please use the style svind.ist with your makeindex program
      # No idea how to do that
      #############################################
      - name: Compile LaTeX document of Springer
        uses: dante-ev/latex-action@latest
        with:
          root_file: header.tex

      - name: Check the created PDF's existence
        uses: andstor/file-existence-action@v2
        with:
          files: header.pdf
          fail: true

      - name: Rename PDF
        run: mv header.pdf article_springer.pdf

      #############################################
      # Regular TeX
      #############################################
      - name: Edit text to show pictures
        run: ./scripts/make_full_article.sh

      - name: Compile normal LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: header.tex

      - name: Check the created PDF's existence
        uses: andstor/file-existence-action@v2
        with:
          files: header.pdf
          fail: true

      - name: Rename PDF
        run: mv header.pdf article_normal.pdf

      #############################################
      # Upload
      #############################################
      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: article_pdfs
          path: article_normal.pdf article_springer.pdf
          if-no-files-found: error

