on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 3 * *"

name: Check spelling

jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2


      #- name: Check spelling
      #  uses: reitermarkus/aspell@main
      #  with:
      #    files: article.tex
      #    args: --lang=en_GB --mode=tex

      - name: Install aspell
        run: sudo apt-get install aspell

      - name: Run spell check
        run: ./scripts/do_spell_check.sh
