on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 3 * *"

name: Check spelling

jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Check spelling
        run: ./scripts/do_check_spelling.sh
